<?php


namespace app\models;


use yii\base\Model;

class ExportForm extends Model
{
    public  $yearMonth;
    public  $sokuhouId;

    /**
     * @return array
     */
    public function rules()
    {

        return [
            ['sokuhouId' ,'integer', 'min' => 1, 'max' => 6],
            ['yearMonth', 'string']
        ]; // TODO: Change the autogenerated stub
    }
}